- name: Lesson5
  hosts: [aws]
  become: yes

  tasks:

    - name: Check ping
      ansible.builtin.ping:

    - name: Update all packages
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
       url: https://download.docker.com/linux/ubuntu/gpg
       state: present

    - name: Add Docker Repository
      apt_repository:
       repo: deb https://download.docker.com/linux/ubuntu focal stable
       state: present

    - name: Install Docker
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'docker-ce', 'docker-ce-cli', 'containerd.io']

    - name: Install Docker Module for Python
      pip:
       name: 
        - docker
        - docker-compose

    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    # - name: Clone git repo
    #   ansible.builtin.git:
    #     repo: https://github.com/alekzander7c4/ITEA_DevOps_lesson_2.git
    #     dest: /home/ubuntu/lesson5
    #     # single_branch: yes
    #     version: main
    
    - name: Copy file
      ansible.builtin.copy:
        src: docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        force: yes

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /home/ubuntu/
      register: output

    - ansible.builtin.debug:
        var: output

